TeamJaBar/modoo-plus

src/main/resources/applicationContext.xml, src/main/webapp/WEB-INF/DispatcherServlet-servlet.xml, src/main/webapp/WEB-INF/web.xml
- DispatcherServlet 추가
- encFilter 추가
- dataSource 추가
- <context:component-scan base-package="com.spring.biz" /> 추가
- <context:component-scan base-package="com.spring.controller" /> 추가
=> 230222 web.xml, applicationContext.xml, DispatcherServlet-servlet.xml 태그 추가 및 생성

pom.xml, src/main/java/com/sping/biz/controller/CartDeleteController.java, src/main/java/com/sping/biz/member/AddressService.java, src/main/java/com/sping/biz/member/AddressServiceImpl.java, src/main/java/com/sping/biz/member/DibService.java, src/main/java/com/sping/biz/member/DibServiceImpl.java, src/main/java/com/sping/biz/member/MemberService.java, src/main/java/com/sping/biz/member/MemberServiceImpl.java, src/main/java/com/sping/biz/member/OrderService.java, src/main/java/com/sping/biz/member/OrderServiceImpl.java, src/main/java/com/sping/biz/product/ProductService.java, src/main/java/com/sping/biz/product/ProductServiceImpl.java
1) CartDeleteController 오타 수정 (import 부분 오타 수정)
2) pom.xml
: QuickView 컨트롤러에서 필요한 GSON 라이브러리 dependency 추가
3) 비즈니스 레이어 구현
: 각 DAO 별 Serivce 인터페이스 및 구현 클래스 추가
=> 230223 오타수정 및 서비스레이어 구현

src/main/webapp/view/plus/admin-board.jsp, src/main/webapp/view/plus/mypage.jsp
1. JSTL 적용
- admin-board.jsp
2. mypage.jsp 
- 캘린더 삭제 및 수정탭 내용 추가
=> 230223 VIEW JSTL 적용, 기능 삭제 및 추가

src/main/webapp/view/plus/match-detail.jsp
=> Feat : match-detail.jsp JSTL 적용

src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp
=> Feat : mymatch, mypage,  jstl 연결 heatder 수정

src/main/webapp/WEB-INF/tags/bottomBar.tag, src/main/webapp/WEB-INF/tags/score.tag, src/main/webapp/assets/js/page/bootstrap-modal.js, src/main/webapp/view/plus/admin-board.jsp, src/main/webapp/view/plus/match-detail.jsp
- match-detail.jsp관련 tag 생성 및 수정
- match-detail.jsp관련 js 내용 수정
- JSTL적용 및 JS 생성
=> 230226 JSTL 적용 및 JS 추가

src/main/webapp/WEB-INF/tags/bottomBar.tag, src/main/webapp/view/plus/match-detail.jsp
=> Feat : bottomBar.tag JSTL 적용, match-detail.jsp 내용 수정

src/main/webapp/WEB-INF/tags/bottomBar.tag, src/main/webapp/view/plus/admin-board.jsp, src/main/webapp/view/plus/match-detail.jsp
- 댓글 삭제, 퇴출하기 ajax 생성
- 선택 단일 삭제 js 구현
- 코드 수정
=> 230227  ajax 생성 및 JS 구현

src/main/webapp/WEB-INF/tags/exp.tag, src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- 회원관리 부분 수정, 신고취소로 변경
(JS 달아야함)
========================
- 신고 처리결과 출력 추가
- el식 마무리
- 관리자일 경우
- 관리자 메뉴 추가
- 신고 게시글 갯수 나오는 부분 수정
=> Feat : admin-sue.jsp, mymatch.jsp, mypage.jsp, sue-detail.jsp, exp.tag, header.tag ( jstl 적용, 버튼 등 수정 )

src/main/java/com/spring/biz/controller/ProductController.java, src/main/java/com/spring/biz/member/AddressDAO.java, src/main/java/com/spring/biz/member/DibDAO.java, src/main/java/com/spring/biz/member/OrderDAO.java, src/main/webapp/WEB-INF/DispatcherServlet-servlet.xml
1) ProductController
- RequestMapping ~.do 로 수정
2)DispatcherServlet-servlet.xml
- 인코딩 설정 추가
3) 찜, 주소, 오더 DAO JdbcTemplate 적용
=> 230227 컨트롤러 코드 수정 및 JdbcTemplate 적용

src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- 게시글 삭제 버튼
-  날짜, 시간 병합
- 넘버링 삭제
- 신청하기, 평가하기 분기처리 ( 안지난 모임이면 취소하기, 지난 모임이면 평가하기 )
- 페이지네이션 버튼 부분 추가
=> Feat : admin-sue.jsp, mypage.jsp, mymatch.jsp, sue-detail.jsp 수정

src/main/java/com/spring/biz/product/ProductDAO.java, src/main/java/com/spring/biz/product/ProductVO.java, src/main/webapp/view/common/mypage.jsp
- JdbcTemplate 적용
- addrsSelect.do > addrsSelectAll.do 수정
=> 230228 ProductDAO JdbcTemplate 적용

src/main/java/com/spring/biz/board/PageDAO.java, src/main/java/com/spring/biz/board/PageService.java, src/main/java/com/spring/biz/board/PageServiceImpl.java, src/main/java/com/spring/biz/board/PageVO.java, src/main/java/com/spring/controller/PageController.java, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- 글이 있을때와 없을때, 분기처리
- 글이 있을때, 없을때 분기와 count 처리
- 페이지네이션 없던거 추가
- 신고 처리 상태에 따른 행동 추가
- 페이지네이션 적용
=> Feat : mypage.jsp, admin-sue.jsp, mymatch.jsp, sue-detail.jsp 수정, 페이지네이션 적용

src/main/java/com/spring/biz/board/PageDAO.java, src/main/java/com/spring/biz/board/PageService.java, src/main/java/com/spring/biz/board/PageServiceImpl.java, src/main/java/com/spring/controller/PageController.java
- 현재 admin-sue.jsp와 mypage만 페이징 연결해둠
=> Feat : 페이징 수정

src/main/java/com/spring/controller/PageController.java, src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- =! 잘못쓴 부분
- 값 넘겨주는 부분
- 등등 자잘한 수정
=> Feat : EL식 자잘한 수정

src/main/java/com/spring/biz/board/PageDAO.java, src/main/java/com/spring/biz/board/PageService.java, src/main/java/com/spring/biz/board/PageServiceImpl.java, src/main/java/com/spring/controller/PageController.java, src/main/webapp/view/plus/mypage.jsp
=> Feat : 페이징 관련 DAO, sql, controller 수정

src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp
- 평가하기 본인 제외 시킴
- 평가하기에 이름이 아닌 아이디로 나오게 변경
- 퇴출하기 버튼 수정 (aNum으로 넘겨주기)
- 게시글 없으면 게시글 없다고 나오게 수정
- 모달창 radio 버튼 mNum 으로 넘겨주기
- 평가하기 부분
평가 했다면 평가완료 하고 버튼 비활성화
- 날짜 td 수정
=> Feat : mypage.jsp, mymatch.jsp, admin-sue.jsp 수정

src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
=> Feat : 페이지네이션 테스트를 위한 수정

src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- 테스트 위해 지정해둔 임시 경로 복원
- assets 앞에 ../로 변경
=> Feat : assets 앞에 ../변경 및 header.tag 테스트 위해 지정해둔 임시 경로 복원

src/main/java/com/spring/biz/board/BoardDAO.java, src/main/java/com/spring/biz/board/BoardService.java, src/main/java/com/spring/biz/board/BoardServiceImpl.java, src/main/java/com/spring/biz/board/BoardVO.java, src/main/java/com/spring/biz/board/PageDAO.java, src/main/java/com/spring/biz/board/PageService.java, src/main/java/com/spring/biz/board/PageServiceImpl.java, src/main/java/com/spring/biz/board/PageVO.java, src/main/webapp/view/plus/mypage.jsp
- 페이지네이션 관련하여 수정
PageVO, PageDAO, MyPageController, BoardDAO, BoardService, BoardServiceImpl, mypage.jsp 수정
=> 230306 페이지네이션

src/main/webapp/view/plus/admin-board.jsp, src/main/webapp/view/plus/match-detail.jsp
=> 20230306 카테고리 필터링 기능 구현 및 오타수정

src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/mymatch.jsp
- 취소하기 버튼 ajax로 변경
- 평가하기 버튼 mNum 보내주게 수정
- 드롭다운 메뉴 수정
- 로그인하지 않은 회원이면 메뉴 안 나오게
=> Feat : mymatch.jsp, header.tag 수정

src/main/webapp/view/plus/admin-sue.jsp
=> Feat : admin-sue.jsp. 필터 버튼 누르면 색 바뀜, ajax로 값 넘겨짐

src/main/webapp/view/plus/admin-sue.jsp
- 버튼 뱃지 변경
- 데이터 없을 때 페이징 구역 수정
=> Feat : admin-sue.jsp 버튼 뱃지 변경, 데이터 없을때 페이징구역 수정

src/main/webapp/view/plus/admin-sue.jsp
=> fix : script, link 경로 수정

src/main/webapp/view/plus/match-detail.jsp
- 비로그인 시 댓글 비활성화 기능 구현 및 오타 수정
=> Feat : match-detail.jsp 비로그인 시 댓글 비활성화 기능 구현 및 오타 수정

src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- ajax로 넘겨주는 값 변경
- admin-sue.jsp, sue-detail.jsp 버튼, 크기 등 조절
=> Feat : css수정, mypage.jsp ajax로 넘겨주는 값 변경

src/main/webapp/WEB-INF/tags/bottomBar.tag, src/main/webapp/assets/css/match-detail.css, src/main/webapp/view/plus/match-detail.jsp
- 버튼관련 로직 수정 및 오류 수정
- 매칭상세화면 바텀 바 css수정
=> 20230309 매칭디테일관련 로직 및 오류 수정

src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp
=> Feat : mymatch.jsp 모달창 ajax로 수정

src/main/webapp/view/plus/mymatch.jsp
=> 230310 평가하기 모달창 디자인 수정

src/main/java/com/spring/biz/member/MemberVO.java, src/main/webapp/view/plus/mymatch.jsp
- 모든 버튼, 모달 기능 구현완료
- toString 추가
=> Feat : mymatch.jsp 모든 버튼,모달 기능 구현 완료

src/main/webapp/view/plus/mymatch.jsp
- 제목 누르면 detail 페이지로 이동
- 인원 누르면 현재 참여 인원 modal창 띄움
=> Feat : mymatch.jsp 제목 누르면 detail로 이동, 인원 누르면 현재 참여 인원 modal창으로 띄우기

src/main/webapp/assets/js/page/modules-calendar.js, src/main/webapp/view/plus/mymatch.jsp
=> Feat : mymatch.jsp 캘린더 데이터 적용 및 언어 변경

src/main/java/com/spring/biz/board/BoardDAO.java, src/main/java/com/spring/controller/BoardController.java, src/main/java/com/spring/controller/MyPageController.java, src/main/webapp/WEB-INF/tags/bottomBar.tag, src/main/webapp/view/plus/match-insert.jsp
[Model]
1) Insert 문 수정
2) Update 문 수정
3) 가장 최근에 삽입한 글 가져오는 SELECTONE_LATLEY 추가
[View]
1) 처음 맵 띄울시 일부만 로드되는 버그 수정
: 모달창 띄울 때 map.relayout()하는 script 추가
2) ckeditor url 요청 수정
3) 위도/경도 값 받아온느 코드 수정
[Controller]
1) insertBoard 수정
2) uploadImg 추가
3) updateBoard 수정
=> 230313 게시글 INSERT / UPDATE

src/main/java/com/spring/biz/board/ApplicantDAO.java, src/main/webapp/WEB-INF/tags/score.tag, src/main/webapp/view/plus/mypage.jsp
- 모달창 띄우기 성공
- score값 안넘어 오는거 추가
- 오타수정
=> Feat : mypage 모달창 띄우기 성공

src/main/webapp/assets/js/page/modules-calendar.js, src/main/webapp/view/plus/mymatch.jsp
=>  Feat : mymatch.jsp modules-calendar.js 풀캘린더 시간포멧 설정 변경

src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mypage.jsp
- 각 기능 ajax방식 연결 완료
- el식 fn 수정
=> Feat : mypage.jsp 각 기능 ajax 방식 연결 완료

src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- mypage.jsp
- mymatch.jsp
- admin-sue.jsp
- sue-detail.jsp
- 각 페이지 footer 추가
=> style : 푸터 추가

src/main/java/com/spring/controller/BoardController.java
=> 230313 코드 순서 변경

src/main/webapp/view/plus/admin-sue.jsp
=> Feat : admin-sue.jsp ajax 수정

src/main/java/com/spring/biz/sue/SueDAO.java, src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/sue-detail.jsp
- 페이지 접근 정상 작동
- sue-detail 관련 DAO 수정
=> Feat : sue-detail.jsp 정상출력

src/main/java/com/spring/biz/sue/SueDAO.java
=> Fix : sueDAO SQL문 수정

src/main/webapp/assets/js/page/bootstrap-modal.js, src/main/webapp/view/plus/match-detail.jsp, src/main/webapp/view/plus/match-insert.jsp
- 신고하기 관련 로직 수정 및 정지당한 회원 게시글 및 댓글 블라인드 로직 추가
- 미디어주소 추가 플러그인 삭제 및 정렬
=> 20230314 신고하기 관련 로직 수정 정지당한 회원 게시글, 댓글 블라인드 로직 추가

src/main/java/com/spring/biz/common/ImageUploadUtil.java, src/main/java/com/spring/biz/sue/SueDAO.java, src/main/java/com/spring/controller/BoardController.java, src/main/webapp/view/plus/match-detail.jsp, src/main/webapp/view/plus/match-insert.jsp
1) SueDAO
insert문 수정
2) match-inser.jsp
css 수정
3) boardcontroller
insertSue.do 에 대한 컨트롤러 return 변경
4) match-detail.jsp
form 태그 변경
=> 230314 신고 / 게시글 작성 수정

src/main/webapp/view/plus/board-list.jsp
=> 230314 board-list.jsp CSS 추가

src/main/webapp/view/plus/mypage.jsp
=> style : 테이블 css 수정

src/main/webapp/view/plus/sue-detail.jsp
=> fix : 주석으로 인해 페이지 안들어가지는 에러 수정

src/main/webapp/view/plus/admin-sue.jsp
=> style : admin-sue 테이블 css 수정

src/main/java/com/spring/controller/MyPageController.java, src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/sue-detail.jsp
[1] 상단바 검색 관련 Controller, View 수정
[2] mymatch.jsp 달력 간격 조정
[3] sue-detail.jsp 점수 강등 삭제
=> 230315 상단바 검색 수정 

src/main/java/com/spring/controller/AdminController.java, src/main/webapp/view/plus/admin-board.jsp, src/main/webapp/view/plus/match-detail.jsp, src/main/webapp/view/plus/match-insert.jsp
- 한/영 오토마타 기능 추가
- 로직 수정 및 오타 수정
- 전체(삭제, 네비게이션, 페이지네이션) 자바스크립트 로직 수정
- 보드데이터를 JSON데이터로 보내도록 재수정
=> 20230315 한/영 오토마타 기능 추가 및 로직 수정

pom.xml, src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp
- 페이지네이션 버튼
- 취소하기 버튼 ajax 수정
- 비 로그인시 드랍다운 메뉴 수정
=> feat : 페이지네이션 버튼, 취소하기, 비 로그인시 헤더 드랍다운메뉴 수정

src/main/webapp/view/plus/admin-sue.jsp
=> fix : 페이지네이션 버튼 수정

pom.xml
=> fix : javax-mail 중복 제거

src/main/resources/message/messageSource_en.properties, src/main/resources/message/messageSource_ko.properties, src/main/webapp/WEB-INF/tags/header.tag
=> Feat : header 다국어 처리 추가

pom.xml, src/main/resources/applicationContext.xml, src/main/webapp/view/plus/mypage.jsp
=> Feat : 비밀번호 찾기 이메일 API 수정

src/main/java/com/spring/biz/common/EmailSender.java, src/main/java/com/spring/biz/common/EmailVO.java, src/main/java/com/spring/controller/EmailController.java
=> Feat : 이메일 API 관련 M 생성

src/main/webapp/view/plus/match-detail.jsp
=> Feat : match-detail.jsp 정지된 회원과 일반회원 구분 로직 수정

src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mypage.jsp
=> Feat : 테이블 정렬 수정, 매치 상태에 따른 버튼 변경

src/main/java/com/spring/biz/member/MemberDAO.java, src/main/java/com/spring/biz/member/MemberVO.java, src/main/java/com/spring/controller/AccountController.java
=> 230317 로그인 블락 추가

src/main/java/com/spring/controller/AccountController.java
=> feat : 이메일 컨트롤 겹치지 않게 주석처리

src/main/java/com/spring/biz/sue/SueService.java, src/main/java/com/spring/biz/sue/SueServiceImpl.java, src/main/java/com/spring/controller/EmailController.java, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
- EmailCTRL 회원정지시 메일 발송되게 수정
- Service 레이어 수정
- 오타, alt값 등 세부사항 수정
=> Feat : Email API 적용을 위한 CTRL과 Service 레이어 수정, 각 페이지 세부 수정

src/main/java/com/spring/biz/common/EmailSender.java, src/main/resources/applicationContext.xml
=> Feat : EmailSender Repository로 변경

src/main/java/com/spring/biz/board/BoardDAO.java, src/main/java/com/spring/controller/BoardController.java, src/main/java/com/spring/controller/MyPageController.java, src/main/webapp/view/common/header.jsp, src/main/webapp/view/plus/board-list.jsp
무한스크롤 추가
- board-list.jsp : ajax 수정
- BoardDAO : SQL_SELECTALL_MAIN 수정
- BoardController & MypageController 요청 수정
=> 230317 무한스크롤

src/main/resources/applicationContext.xml, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/sue-detail.jsp
- smId로 변경 
- 제목 가운데 정렬 적용 안된 부분 수정
- sNum 넘기기
=> fix : 데이터 보여지는 부분, sNum 넘기는것 수정

src/main/webapp/view/plus/sue-detail.jsp
=> feat : 신고자 나오게 수정

src/main/webapp/WEB-INF/tags/header.tag, src/main/webapp/view/plus/match-detail.jsp
=> feat : boardList 경로 수정

src/main/java/com/spring/biz/sue/SueDAO.java, src/main/webapp/view/common/footerPlus.jsp, src/main/webapp/view/plus/admin-board.jsp, src/main/webapp/view/plus/admin-sue.jsp, src/main/webapp/view/plus/mymatch.jsp, src/main/webapp/view/plus/mypage.jsp, src/main/webapp/view/plus/sue-detail.jsp
=> feat : footer 추가
